Changed funding external id jaxb -> jpa conversion so that reuses existing entities where possible.
This was to fix the following error (when de-duplication occurs during
re-saving of the profile).

java.lang.IllegalArgumentException: Removing a detached instance
org.orcid.persistence.jpa.entities.FundingExternalIdentifierEntity#15299