PD-5955 Fixed jakarta.persistence.TransactionRequiredException
Fixed jakarta.persistence.TransactionRequiredException: Executing an update/delete query] with root cause
jakarta.persistence.TransactionRequiredException: Executing an update/delete query in the ProfileEntityManager and other places with potentially the same issue